// Generated by CoffeeScript 1.4.0
(function() {
  var ImageChanger, root,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  ImageChanger = (function() {

    ImageChanger.prototype.options = {};

    ImageChanger.prototype.queue = [];

    ImageChanger.prototype.images = [];

    ImageChanger.prototype.currentImage = -1;

    ImageChanger.prototype.imageOpacity = 0;

    ImageChanger.prototype.animationInProgress = false;

    ImageChanger.prototype.automaticAnimation = false;

    function ImageChanger(options) {
      this._animateFinished = __bind(this._animateFinished, this);

      this._display = __bind(this._display, this);

      this._addImage = __bind(this._addImage, this);

      this.previous = __bind(this.previous, this);

      this.next = __bind(this.next, this);
      options = options ? options : {};
      this.options = _.defaults(options, {
        imageReader: null,
        viewport: null,
        viewportDimensions: {
          height: -1,
          width: -1
        },
        centerImagesInViewport: true,
        fitImagesToViewPort: false,
        events: {
          click: function() {}
        },
        duration: 500
      });
      this.queue = [];
      this.images = [];
      this.currentImage = -1;
      this._init();
    }

    ImageChanger.prototype.display = function(index, options) {
      var _ref;
      if (options != null ? options.automaticAnimation : void 0) {
        this.automaticAnimation = true;
      }
      if (!this.images[index]) {
        this.options.imageReader.getImage(index, this._addImage);
      } else {
        this._display(index);
      }
      if (!(options != null ? options.overrideEvents : void 0) || options.overrideEvents === !true) {
        return (_ref = this.options.events) != null ? typeof _ref.display === "function" ? _ref.display(index) : void 0 : void 0;
      }
    };

    ImageChanger.prototype.next = function() {
      this.automaticAnimation = true;
      if (this.currentImage + 1 < this.imageCount) {
        return this.display(this.currentImage + 1);
      } else {
        return this.display(0);
      }
    };

    ImageChanger.prototype.previous = function() {
      this.automaticAnimation = true;
      if (this.currentImage > 0) {
        return this.display(this.currentImage - 1);
      } else {
        return this.display(this.imageCount - 1);
      }
    };

    ImageChanger.prototype._init = function() {
      this.imageCount = this.options.imageReader.getImageCount();
      if (this.options.events.click) {
        this.options.viewport.click(this.options.events.click);
      }
      return this.display(0, {
        overrideEvents: true
      });
    };

    ImageChanger.prototype._addImage = function(index, image) {
      this.images[index] = image;
      this._insertImage(image);
      if (this.options.fitImagesToViewPort) {
        this._fitImage(image);
      }
      this._centerImage(image);
      return this._display(index);
    };

    ImageChanger.prototype._display = function(index) {
      this.queue.push(index);
      return this._animate();
    };

    ImageChanger.prototype._insertImage = function(image) {
      this.options.viewport.append(image.image);
      image.image.hide();
      return image.image.css({
        opacity: this.imageOpacity
      });
    };

    ImageChanger.prototype._imageDimensions = function(image) {
      return {
        x: image.width(),
        y: image.height()
      };
    };

    ImageChanger.prototype._calculateEnlargementFactor = function(dimensions1, dimensions2, dimension) {
      return dimensions1[dimension] / dimensions2[dimension];
    };

    ImageChanger.prototype._fitImage = function(image) {
      var enlargementFactor, heightToSet, imageDimensions, longestDimensionImage, otherDimensionImage, viewportDimensions, widthToSet;
      viewportDimensions = this._imageDimensions(this.options.viewport);
      imageDimensions = this._imageDimensions(image.image);
      longestDimensionImage = imageDimensions.x >= viewportDimensions.x ? 'x' : imageDimensions.y > viewportDimensions.y ? 'y' : imageDimensions.x >= imageDimensions.y ? 'x' : 'y';
      otherDimensionImage = longestDimensionImage === 'x' ? 'y' : 'x';
      enlargementFactor = this._calculateEnlargementFactor(viewportDimensions, imageDimensions, longestDimensionImage);
      if ((enlargementFactor * parseInt(imageDimensions[otherDimensionImage])) > viewportDimensions[otherDimensionImage]) {
        enlargementFactor = this._calculateEnlargementFactor(viewportDimensions, imageDimensions, otherDimensionImage);
      }
      widthToSet = Math.round(imageDimensions.x * enlargementFactor);
      heightToSet = Math.round(imageDimensions.y * enlargementFactor);
      return image.image.css({
        width: widthToSet,
        height: heightToSet
      });
    };

    ImageChanger.prototype.calculateOffset = function(dimensions1, dimensions2, dimension) {
      return Math.floor((dimensions1[dimension] - dimensions2[dimension]) / 2);
    };

    ImageChanger.prototype._centerImage = function(image) {
      var imageDimensions, viewportDimensions;
      viewportDimensions = this._imageDimensions(this.options.viewport);
      imageDimensions = this._imageDimensions(image.image);
      return image.image.css({
        position: "absolute",
        left: this.calculateOffset(viewportDimensions, imageDimensions, 'x'),
        top: this.calculateOffset(viewportDimensions, imageDimensions, 'y')
      });
    };

    ImageChanger.prototype._animate = function() {
      var next;
      if (this.animationInProgress || this.queue.length === 0) {
        return -1;
      }
      this.animationInProgress = true;
      next = this.queue[0];
      this.queue = _.without(this.queue, next);
      if (next === this.currentImage) {
        this._animateFinished();
        return -1;
      } else {
        return next;
      }
    };

    ImageChanger.prototype._animateFinished = function() {
      var _this;
      _this = this;
      return window.setTimeout(function() {
        _this.animationInProgress = false;
        if (_this.queue.length > 0) {
          return _this._animate();
        }
      }, 100);
    };

    return ImageChanger;

  })();

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  root.ImageChanger = ImageChanger;

}).call(this);
