// Generated by CoffeeScript 1.4.0
(function() {
  var ImageFader, root,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  ImageFader = (function(_super) {

    __extends(ImageFader, _super);

    function ImageFader() {
      return ImageFader.__super__.constructor.apply(this, arguments);
    }

    ImageFader.prototype._animate = function() {
      var next;
      next = ImageFader.__super__._animate.apply(this, arguments);
      if (next > -1) {
        if (this.currentImage > -1) {
          this.images[this.currentImage].image.animate({
            opacity: 0
          }, this.options.duration);
        }
        this.images[next].image.show();
        this.images[next].image.animate({
          opacity: 1,
          useTranslate3d: true
        }, this.options.duration, this._animateFinished);
        return this.currentImage = next;
      }
    };

    return ImageFader;

  })(ImageChanger);

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  root.ImageFader = ImageFader;

}).call(this);
